class AppConstants {
  static const String appName = 'OneVisit';
  static const String tagline = 'SIMPLER VISITS, BRIGHTER DAYS';
  static const String logoAsset = 'assets/images/logo.png';
}

enum AppLanguage {
  english,
  malayalam,
  hindi,
}

class AppLocalization {
  static final Map<AppLanguage, Map<String, String>> _strings = {
    AppLanguage.english: {
      'appName': 'OneVisit',
      'tagline': 'SIMPLER VISITS, BRIGHTER DAYS',
      'goodMorning': 'Good Morning',
      'searchPlaceholder': 'Search services, offices...',
      'bannerTitle': 'One App. Many Services.',
      'bannerSubtitle': 'Skip the queue, complete forms digitally, and visit only when called.',
      'quickActions': 'Quick Actions',
      'findService': 'Find a Service',
      'fillForm': 'Fill a Form',
      'bookToken': 'Book Token',
      'myTokens': 'My Tokens',
      'activeToken': 'Upcoming Token',
      'recentApplications': 'Recent Applications',
      'peopleAhead': 'People Ahead',
      'estWait': 'Est. Waiting Time',
      'liveStatus': 'Live Queue Status',
      'viewQR': 'View QR Code',
      'navHome': 'Home',
      'navServices': 'Services',
      'navTokens': 'My Tokens',
      'navApps': 'Applications',
      'navProfile': 'Profile',
      'categories': 'Categories',
      'allServices': 'All Government Services',
      'startApplication': 'Start Application',
      'nowServing': 'Now Serving',
      'yourToken': 'Your Token',
      'counter': 'Counter',
      'cancelToken': 'Cancel Token',
      'accessibility': 'Accessibility Settings',
      'helpCenter': 'Help & Support Center',
      'adminPortal': 'Admin Portal',
      'staffPortal': 'Staff Calling Counter',
    },
    AppLanguage.malayalam: {
      'appName': 'വൺവിസിറ്റ്',
      'tagline': 'ലളിതമായ സന്ദർശനം, തിളക്കമുള്ള ദിനങ്ങൾ',
      'goodMorning': 'സുപ്രഭാതം',
      'searchPlaceholder': 'സേവനങ്ങളും ഓഫീസുകളും തിരയുക...',
      'bannerTitle': 'ഒരു ആപ്പ്. ഒട്ടനവധി സേവനങ്ങൾ.',
      'bannerSubtitle': 'വരി നിൽക്കാതെ ഡിജിറ്റലായി ഫോം പൂരിപ്പിക്കൂ, വിളിക്കുമ്പോൾ മാത്രം എത്തൂ.',
      'quickActions': 'പ്രധാന പ്രവർത്തനങ്ങൾ',
      'findService': 'സേവനം കണ്ടെത്തുക',
      'fillForm': 'ഫോം പൂരിപ്പിക്കുക',
      'bookToken': 'ടോക്കൺ ബുക്ക് ചെയ്യുക',
      'myTokens': 'എന്റെ ടോക്കണുകൾ',
      'activeToken': 'വരാനിരിക്കുന്ന ടോക്കൺ',
      'recentApplications': 'സമീപകാല അപേക്ഷകൾ',
      'peopleAhead': 'മുന്നിലുള്ള ആളുകൾ',
      'estWait': 'പ്രതീക്ഷിക്കുന്ന സമയം',
      'liveStatus': 'തത്സമയ ക്യൂ നില',
      'viewQR': 'QR കോഡ് കാണുക',
      'navHome': 'ഹോം',
      'navServices': 'സേവനങ്ങൾ',
      'navTokens': 'ടോക്കണുകൾ',
      'navApps': 'അപേക്ഷകൾ',
      'navProfile': 'പ്രൊഫൈൽ',
      'categories': 'വിഭാഗങ്ങൾ',
      'allServices': 'എല്ലാ സർക്കാർ സേവനങ്ങളും',
      'startApplication': 'അപേക്ഷ ആരംഭിക്കുക',
      'nowServing': 'ഇപ്പോൾ സേവനം നൽകുന്നത്',
      'yourToken': 'നിങ്ങളുടെ ടോക്കൺ',
      'counter': 'കൗണ്ടർ',
      'cancelToken': 'ടോക്കൺ റദ്ദാക്കുക',
      'accessibility': 'ലളിത പ്രവേശന ക്രമീകരണങ്ങൾ',
      'helpCenter': 'സഹായ കേന്ദ്രം',
      'adminPortal': 'അഡ്മിൻ പോർട്ടൽ',
      'staffPortal': 'സ്റ്റാഫ് കൗണ്ടർ',
    },
    AppLanguage.hindi: {
      'appName': 'वनविज़िट',
      'tagline': 'सरल मुलाक़ातें, बेहतर दिन',
      'goodMorning': 'शुभ प्रभात',
      'searchPlaceholder': 'सेवाएं, कार्यालय खोजें...',
      'bannerTitle': 'एक ऐप। अनेक सेवाएं।',
      'bannerSubtitle': 'कतार से बचें, डिजिटल फॉर्म भरें और केवल बुलाए जाने पर जाएं।',
      'quickActions': 'त्वरित कार्य',
      'findService': 'सेवा खोजें',
      'fillForm': 'फॉर्म भरें',
      'bookToken': 'टोकन बुक करें',
      'myTokens': 'मेरे टोकन',
      'activeToken': 'आगामी टोकन',
      'recentApplications': 'हाल के आवेदन',
      'peopleAhead': 'आगे मौजूद लोग',
      'estWait': 'अनुमानित प्रतीक्षा समय',
      'liveStatus': 'लाइव कतार स्थिति',
      'viewQR': 'QR कोड देखें',
      'navHome': 'होम',
      'navServices': 'सेवाएं',
      'navTokens': 'टोकन',
      'navApps': 'आवेदन',
      'navProfile': 'प्रोफ़ाइल',
      'categories': 'श्रेणियां',
      'allServices': 'सभी सरकारी सेवाएं',
      'startApplication': 'आवेदन शुरू करें',
      'nowServing': 'वर्तमान सेवा',
      'yourToken': 'आपका टोकन',
      'counter': 'काउंटर',
      'cancelToken': 'टोकन रद्द करें',
      'accessibility': 'सरल अभिगम्यता',
      'helpCenter': 'सहायता केंद्र',
      'adminPortal': 'एडमिन पोर्टल',
      'staffPortal': 'स्टाफ काउंटर',
    },
  };

  static String tr(String key, AppLanguage lang) {
    return _strings[lang]?[key] ?? _strings[AppLanguage.english]?[key] ?? key;
  }
}
